### PR TITLE
Update PS! Pokedex for Gen 9

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by Zarel** [comment]
AFAICT this is superseded by #23; please correct me if that's wrong.

**Comment by KrisXV** [comment]
> AFAICT this is superseded by #23; please correct me if that's wrong.

#23 doesn't actually add any new gen 9 content, it just removes the hardcodes. I would've preferred to rebase this.

**Comment by Zarel** [comment]
Oh, I see!

**Comment by Zarel** [comment]
Can you still rebase this?

**Comment by KrisXV** [comment]
Oh yeah I forgot, I'll do that in a second

**Comment by KrisXV** [comment]
@zarel done

**Comment by Zarel** [comment]
Thanks!

**Pull request merged**
